apiVersion: apps/v1
kind: Deployment
metadata:
    name: tweetapi-deployment
    labels:
      app: tweetapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tweetapi      
  template:
    metadata:
      labels:
        app: tweetapi
    spec:
      containers:
        - name: tweetapi
          image: tweetimageacr.azurecr.io/tweetapi:v2
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
      imagePullSecrets:
            - name: acr-secret    

---

apiVersion: v1
kind: Service
metadata:
  name: tweetapiservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
      app: tweetapi      

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: tweetapi-hpa
spec:
    maxReplicas: 10
    minReplicas: 3
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: tweetapi-deployment
    targetCPUUtilizationPercentage: 90
    
    