apiVersion: apps/v1
kind: Deployment
metadata:
    name: tweetapi-deployment
    labels:
      app: tweetapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweetapi      
  template:
    metadata:
      labels:
        app: tweetapi
    spec:
      containers:
        - name: tweetapi
          image: tweetappimagesacr.azurecr.io/tweetapi:v2
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:
            - name: tweet-app-secret    

---

apiVersion: v1
kind: Service
metadata:
  name: tweetapiservice
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
      app: tweetapi      

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: tweetapi-hpa
spec:
    maxReplicas: 1
    minReplicas: 1
    scaleTargetRef:
        apiVersion: apps/v1
        kind: Deployment
        name: tweetapi-deployment
    targetCPUUtilizationPercentage: 90
    
    